services:

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      TZ: "${TZ-Europe/London}"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      TZ: "${TZ-Europe/London}"
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:8080 || exit 1"
      start_period: 30s

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command: [ "--config=/etc/otel-collector-config.yml" ]

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

  consumer-btc:
    image: docker.mycompany.com/kafka-docker-consumer
    container_name: consumer-btc
    depends_on:
    - kafka-ui
    - otel-collector
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_GROUP_ID: "my-group"
      TOPICS: "BTC"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_SERVICE_NAME: "kafka-consumer-btc"
      SPRING_APPLICATION_NAME: "kafka-consumer-btc"

  consumer-ltc:
    image: docker.mycompany.com/kafka-docker-consumer
    container_name: consumer-ltc
    depends_on:
    - kafka-ui
    - otel-collector
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_GROUP_ID: "my-group"
      TOPICS: "LTC"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_SERVICE_NAME: "kafka-consumer-ltc"
      SPRING_APPLICATION_NAME: "kafka-consumer-ltc"

  producer:
    image: docker.mycompany.com/kafka-docker-producer:latest
    container_name: producer
    depends_on:
    - consumer-btc
    - consumer-ltc
    - otel-collector
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      INITIAL_DELAY: 30000
      INTERVAL: 3000
      TOPICS: "BTC,LTC"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_SERVICE_NAME: "kafka-producer"
