{
 "title": "Crypto Kafka Logs",
 "tags": [
  "kafka",
  "crypto"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\"kafka-.+\"}"
    }
   ]
  },
  {
   "title": "Producer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Consumer BTC",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"kafka-consumer-btc\"}"
    }
   ]
  },
  {
   "title": "Consumer LTC",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"kafka-consumer-ltc\"}"
    }
   ]
  }
 ]
}